matrix:
  include:
    - os: linux
      dist: xenial
      language: generic
      env:
        - ROBERTO_CONDA_PINNING="python 3.6"
        - ROBERTO_DEPLOY_BINARY=1
    - os: linux
      dist: xenial
      language: generic
      env:
        - ROBERTO_CONDA_PINNING="python 3.7"
        - ROBERTO_DEPLOY_NOARCH=1
        - ROBERTO_DEPLOY_BINARY=1
    - os: osx
      osx_image: xcode9.4
      language: generic
      env:
        - ROBERTO_CONDA_PINNING="python 3.6"
        - ROBERTO_DEPLOY_BINARY=1
    - os: osx
      osx_image: xcode9.4
      language: generic
      env:
        - ROBERTO_CONDA_PINNING="python 3.7"
        - ROBERTO_DEPLOY_BINARY=1

env:
  global:
    # Install conda in a *sub*directory of a directory cached by travis.
    - ROBERTO_CONDA_BASE_PATH=${HOME}/cache/miniconda3
    # Tell Roberto to upload coverage results
    - ROBERTO_UPLOAD_COVERAGE=1
    # Build conda packages outside the miniconda tree, to avoid caching.
    # This makes it possible to still deploy packages after cache cleaning.
    - CONDA_BLD_PATH=${HOME}/conda-bld
    # Tell roberto which branch is being merged into, in case of a PR.
    - ROBERTO_MERGE_BRANCH=${TRAVIS_BRANCH}
    # Debugging options
    # - HUB_VERBOSE=1

    # GITHUB_TOKEN
    # yamllint disable-line rule:line-length
    - secure: "ufek0lzQcoNnf6N3DTyTGlgpUw9twldah8dG96s2VgP4PXugBHAfXmmswCqPcSQrHoDE50NWjZjHT01z+E+nDPrPe/eZdUy9wjl++09jSSueZOWyDteR9wbpgC4K4+lRT2bQW9EAJSngSL4wFHrvdruk2JQY227aQVAlo8IDxcO6CScHg/hPD9PvwMHYwwPISorwF4r2zbwRcGgBEY2Aei9vELWn7zJcW1dXBB1LTbvwNj7lb7Nlbn8cnW2uOafuTnbz5jEdumcDXq1LqyUVx5oOpXSTM0+IcdxTYWgsNSK3b+1Be/d3vhVxQKCux6a9FigwT6VXkkSv6eA5kO5oTCLP5YsONiEIc+5fPlqL4OtsdGWw63oNcG0FMVMnIVf44ECEER9+8LXn864tedjnh6PCUIXdlXrcxlsXzEkA4h06Oez7gg5YmYUzMAN/mbQoqJ946TEaABdCcBkWYqBcSSSzEhLMs5uv3YeAYzKVyd4lPHQNa9pyxLA/iTJ9a1VTy6MWLUe/PS3pg9LALx22v+nBkGwhx7Wv0uLMPe1yjlrdjt6/K6wdVM02pf1guZcIj7E5eMHPPRaBEFKLd9D5JWd1XUWFPjXptufe0ilg3oQ4mZtHPuTpNXEAQFGO7U4/bSX1M2uAFkKhNa6XD/ED6lf/axr5Mae7Yr8ujeKIdfE="
    # ANACONDA_API_TOKEN
    # yamllint disable-line rule:line-length
    - secure: "hC1rdCdCxtX4OJG/eodYxIB+NYNq5Zxwi2ttVue9qZiUIvHNTRmphf90aqGBnZ8INrHXDGW+GXLOYlvbVvs+xEl6dOnbldh/Cna3xWMFJbWVDWFtqSMi58e3JilxJEq25bT4PbXf4jSp9H5Py19L4UgjyNRq65+hbgPO5RLMJ+KGLLcCnYP7zQZsc6mB64JRRGXrVdwtc85Pd6GD+ILKhxsed/l31pqSISjfHcgDhHm8bbG/s7UWFHX/55xLaqeUR0g1nnbdBjHhGiicp1YkB5DsgoqPhYfAzrd8UHffaxaJKpVXfeqs/99Db0yg1eGENbsyOIC1tqXZ+OWGoFYV+phPjW/bWD5S9vzjz4N52hoFK1h8sbVgPS14vrek5ICeiiykpicllJtEGEnSc8eHXPxjDG7qegAfb/f32KrLQ5KsW/znS3VrXT/rPQDbA7VZg3OcDzkAcs6/olLZSRfODH5D4qFhqmZZY9Qsciah9TFdbTxSYC62IPVatT8p45jah21afatyi9WU4t4E6LK95mUOZl5r3+CZ/MQ6LRZESopdiXlpL2LvTtJJCbsjGFx+VZfInvnJyhSTZJqWzxevRSWfyOGAEMMkoDMa2CnltHiLX8l32GDsqq+uNtpHeShkxJjewJ6qwo5G3dRt569VbEq/QFmlD3RknNG0/BEXFP0="
    # TWINE_PASSWORD
    # yamllint disable-line rule:line-length
    - secure: "g/ymb9fz+T2yEOz2IGpnPI9lQQ+MLT+qfnRXHH+hom815yMmXOb3s9Gy+6ruPncD0kws7CZRxikAq6qaynJ2d/b0cIXY8MdvFumW0MRLJCzs5iqdRLCAH7VgQ0cl6Ee2BdUPn9bjK23YaJLU5PplAfBIH5jHV7miDxqhEyoRW0GJpf4A4CXu+3yuyS7l2ETzpOObaNiRos6OqAMVQ/7hHl2dRhddAwNwwaFDY7Gf2JWM42Oueoufbk716LOtsNzt1a9Jn2sqJlTvPaz15idpw2rTv2boHkz9hjCAPu6ZdfykR9F4rUu4EmolYwkeBJiW4DymPIBEQJN0KuuxPXEoVW8Q+Mcy/OHtwGjabOnScA1Ki69l4VTs5valxynw40XsegvvzqiAjTKoftPEl7NMBsEzXKHW5slDMEVS1AdAC1RciO/J3uxI6jRdbbHlKY1AFJCwB5E5zh8D2aPrXG1Opx/9uFkEPFMtBT2ZHRq+uEFY129URlY6fc7O401I4dCQU6GzjsWe5Cv2Tjsl9+GmMBWhwl4eM5IvN/x2LO3TCZDXXaZ+y7GrnwgeQaKfGXu6lUEmog5L+0ldJvqe3+EyURYSpwZblHN1JoqbgmWkfiVoRHNAD2dz7w9JTJFE66dnZJkESFFhJPUoUFQSedPKu5HV2GtCMoEVYJ7hOudAljo="
    - TWINE_USERNAME: theochem

cache:
  # More time is needed for caching due to the sheer size of the conda env.
  timeout: 1000
  directories:
    - ${HOME}/cache

install:
  # Disable deployment when TRAVIS_TAG is not set. This avoids duplicate deployments.
  - if [[ -z $TRAVIS_TAG ]]; then
      export ROBERTO_DEPLOY_BINARY=0 ROBERTO_DEPLOY_NOARCH=0;
    fi
  # Get a basic python 3 with pip to run roberto
  - python3 --version
  - wget --no-clobber -O ${HOME}/cache/get-pip.py https://bootstrap.pypa.io/get-pip.py || true
  - python3 ${HOME}/cache/get-pip.py --user
  - python3 -m pip install 'roberto<2.0.0' --user

script:
  # Instead of simply calling `rob`, we do something that always works on osx too.
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      python3 -m roberto robot;
    else
      python3 -m roberto;
    fi

before_cache:
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/conda-bld
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/locks
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/pkgs
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/var
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/envs/*/conda-bld
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/envs/*/locks
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/envs/*/pkgs
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/envs/*/var
